name: core
publish_to: "none"
description: Core module for My Pets
version: 1.0.0
environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  path: ^1.9.1
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
